on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

jobs:
    run: |
      curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/khora-berlin/website/dispatches
