on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

jobs:
    run: |
      curl -X POST https://api.github.com/repos/khora-berlin/website/dispatches \
      -H "Accept: application/vnd.github.v3+json" \
      -u ${{ secrets.PAT_TOKEN }} \
      -d '{"event_type": "build_repo"}'
