on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

jobs:
    run: |
      curl -X POST https://api.github.com/repos/khora-berlin/website//dispatches \
      -H 'Accept: application/vnd.github.everest-preview+json' \
      -u ${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}} \
      --data '{"event_type": "build_repo"}'
     
